version: '3.8'

services:
  kanban-app:
    build: .
    container_name: kanban_app
    ports:
      - "3334:3333"
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
